# MCU name
BOOTMAGIC_ENABLE     = yes      # Enable Bootmagic Lite
MOUSEKEY_ENABLE      = no       # Mouse keys
EXTRAKEY_ENABLE      = yes      # Audio control and System control
CONSOLE_ENABLE       = no       # Console for debug
COMMAND_ENABLE       = yes      # Commands for debug and configuration
NKRO_ENABLE          = yes      # Enable N-Key Rollover
BACKLIGHT_ENABLE     = no       # Enable keyboard backlight functionality
AUDIO_ENABLE         = no       # Audio output
RGBLIGHT_ENABLE      = no       # Enable WS2812 RGB underlight.
OLED_ENABLE          = no
OLED_DRIVER          = no       # OLED display
SPLIT_KEYBOARD       = no
COMBO_ENABLE         = no
KEY_OVERRIDE_ENABLE  = yes
UNICODE_ENABLE       = no
UNICODEMAP_ENABLE    = yes
WPM_ENABLE           = no
DEFERRED_EXEC_ENABLE = yes
TAP_DANCE_ENABLE     = yes
CAPS_WORD_ENABLE     = yes
AUTOCORRECT_ENABLE   = yes
