BOOTMAGIC_ENABLE = yes     # Enable Bootmagic Lite
TAP_DANCE_ENABLE = yes
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
NKRO_ENABLE = yes          # Nkey Rollover
BACKLIGHT_ENABLE = no      # Enable keyboard backlight functionality
MIDI_ENABLE = no           # MIDI controls
AUDIO_ENABLE = no          # Audio output on port C6
UNICODE_ENABLE = no        # Unicode
BLUETOOTH_ENABLE = no      # Enable Bluetooth with the Adafruit EZ-Key HID
RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
SLEEP_LED_ENABLE = no    # Breathing sleep LED during USB suspend
OLED_ENABLE = no
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
